version: '3.7'
services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fint-personvern-kodeverk-adapter
    ports:
      - "5432:5432"
    restart: unless-stopped
