apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  labels:
    app.kubernetes.io/component: adapter
    app.kubernetes.io/instance: fint-personvern-kodeverk-adapter-db_fintlabs_no
    app.kubernetes.io/name: fint-personvern-kodeverk-adapter-db
    app.kubernetes.io/part-of: fint-core
    app.kubernetes.io/version: latest
    fintlabs.no/org-id: fintlabs.no
    fintlabs.no/team: core
  name: fint-personvern-kodeverk-adapter-db
  namespace: fintlabs-no
spec:
  database:
    database: fint-core
  image: ghcr.io/fintlabs/fint-personvern-kodeverk-adapter:latest
  imagePullPolicy: Always
  onePassword:
    itemPath: vaults/aks-beta-vault/items/fint-personvern-kodeverk-adapter
  orgId: fintlabs.no
  port: 8080
  replicas: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  restartPolicy: Always
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
