apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-personvern-kodeverk-adapter
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-personvern-kodeverk-adapter
    app.kubernetes.io/instance: fint-personvern-kodeverk-adapter_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  orgId: fintlabs.no
  onePassword:
    itemPath: vaults/aks-alpha-vault/items/fint-personvern-kodeverk-adapter
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
