apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: visma-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-personvern-kodeverk-adapter
  app.kubernetes.io/instance: fint-personvern-kodeverk-adapter_visma_no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: adapter
  app.kubernetes.io/part-of: fint-core
  fintlabs.no/team: core
  fintlabs.no/org-id: visma.no
patches:
  - patch: |-
      - op: replace
        path: "/metadata/labels/app.kubernetes.io~1instance"
        value: "fint-personvern-kodeverk-adapter_visma_no"
      - op: replace
        path: "/spec/orgId"
        value: "visma.no"
    target:
      kind: Application
      name: fint-personvern-kodeverk-adapter
