apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-personvern-kodeverk-adapter
  namespace: rogfk-no
  labels:
    app.kubernetes.io/name: fint-personvern-kodeverk-adapter
    app.kubernetes.io/instance: fint-personvern-kodeverk-adapter_rogfk_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: rogfk.no
spec:
  orgId: rogfk.no
  image: ghcr.io/fintlabs/fint-personvern-kodeverk-adapter-database:latest
  env:
    - name: fint.adapter.base-url
      value: https://beta.felleskomponent.no
  onePassword:
    itemPath: vaults/aks-beta-vault/items/fint-personvern-kodeverk-adapter
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
