create table periode_entity
(
    id          int8 generated by default as identity,
    beskrivelse varchar(255),
    slutt       timestamp,
    start       timestamp not null,
    primary key (id)
);
create table personopplysning_entity
(
    kode       varchar(255) not null,
    navn       varchar(255) not null,
    passiv     boolean,
    system_id  varchar(255) not null,
    periode_id int8,
    primary key (kode)
);
alter table if exists personopplysning_entity add constraint UK_jikq7bbb9qv6qpw0vodl61vrm unique (system_id);
alter table if exists personopplysning_entity add constraint FK68k4qmmrxjwed6oj94iastxin foreign key (periode_id) references periode_entity;
