apiVersion: apps/v1
kind: Deployment
metadata:
  name: fint-personvern-kodeverk-adapter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      restartPolicy: Always
      containers:
        - image: ghcr.io/fintlabs/fint-personvern-kodeverk-adapter:sha-0000000
          name: fint-personvern-kodeverk-adapter
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: fint-personvern-kodeverk-adapter
            - secretRef:
                name: fint-personvern-kodeverk-adapter
