apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-adapter-personvern-kodeverk
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-adapter-personvern-kodeverk
    app.kubernetes.io/instance: fint-adapter-personvern-kodeverk_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: adapter
    app.kubernetes.io/part-of: fint-core
    fintlabs.no/team: core
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-adapter-personvern-kodeverk:latest
  imagePullPolicy: Always
  onePassword:
    itemPath: aks-api-vault/fint-personvern-kodeverk-adapter
  database:
    database: fint-adapter-personvern-kodeverk
  resources:
    limits:
      memory: 512Mi
      cpu: 500m
    requests:
      memory: 256Mi
      cpu: 250m
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
